name = "event-agent-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "event-agent-db"
database_id = "0c8f58e2-f410-4f16-9d6c-55e79716f679"

[[kv_namespaces]]
binding = "KV"
id = "05da99d816ec4a9d817b513a2110cdda"

# Cloudflare Workers AI
[ai]
binding = "AI"
